<?php
/**
 * Redirect Users
 */
function redirect_after_application_menu_alter(&$items){
  global $user;
  $uid = $user->uid;
  $rolesForUsers = array(
    3 => 'Band Entry',
    5 => 'Equestrian Entry',
    9 => 'Media Entry',
  );
  $combined = array_intersect($rolesForUsers, $user->roles);
  if($combined){
    $userNodeSearch = new EntityFieldQuery(); 
    $userNodeSearchResult = $userNodeSearch->entityCondition('entity_type', 'node')
      ->propertyCondition('uid', $uid)
      ->propertyCondition('type', 'display_application', '<>')
      ->execute();
    if(count($userNodeSearchResult) > 0){
      $items['node/add/band-application']['access callback'] = FALSE;
      $items['node/add/equestrian-group-application']['access callback'] = FALSE;
      $items['node/add/float-application']['access callback'] = FALSE;
      $items['node/add/media-application']['access callback'] = FALSE;
      $items['node/add/media-attendee']['access callback'] = FALSE;
    }
  }
}


/**
 * Implementation of hook_form_alter
 * Adds additional submission information.
 */
function redirect_after_application_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'band_application_node_form'){
    $form['#submit'][] = 'redirect_after_application_form_submit';
  }
}

function redirect_after_application_form_submit($form, &$form_state){
  if(!$form_state['values']['field_submit_application']['und'][0]['value']){
    drupal_set_message('While your application has been saved, it has <strong>NOT</strong> been submitted for review. Should you wish to submit it for review, please check the "Submit Application For Review" checkbox at the bottom of the application.', 'warning');
  }else{
    drupal_set_message('Your application has been both saved and submitted for review.', 'warning');
  }
}