<?php
/**
* Implements Hook menu
**/

function email_by_role_menu(){
	$items = array();

	$items['admin/structure/email-by-role'] = array(
		'title' => t('Email By Role'),
		'type' => MENU_NORMAL_ITEM,
		'description' => t('Send Email by Role'),
		'page callback' => 'drupal_get_form',
    'page arguments' => array('email_by_role_form'),
		'access arguments' => array('administer email by role'),
	);

	return $items;
}

/**
 * Implements hook_permission(). 
 */
function email_by_role_permission(){ 
	return array(
		'administer email by role' => array(
			'title' => t('Administer Email by Role Module'),
		),
	);
}

function email_by_role_form($form, &$form_state){
	GLOBAL $user;
	drupal_set_title('Email By Role');
  

	//An Array of options for ToR Admins to select the role to email
  $torAdminRoleOptions = array(
  	3 => 'Band Entrants',
  	5 => 'Equestrian Entrants',
  	7 => 'Float Entrants',
  	9 => 'Media Entrants',
  );

  //An Array that outlines who each admin is emailing
	$torAdminTitleOptions = array(
  	4 => 'Band Entrants',
  	6 => 'Equestrian Entrants',
  	8 => 'Float Entrants',
  	10 => 'Media Entrants',
  );

	//Array of User Role IDs to pass into the query
	$userRoles = array(
		4 => 3,
		6 => 5,
		8 => 7,
		10 => 9,
		17 => array(3, 5, 7, 9),
	);

	$roleToEmail = '';
	$uids = array();
	$emailsArray = array();

	//Query for relevant users
	foreach($user->roles as $userRoleID => $userRoleName){
		if($userRoleID != 2 && $userRoleID != 17){
		  $query = 'SELECT DISTINCT(ur.uid) 
		  	FROM {users_roles} AS ur
		  	WHERE ur.rid IN (:rids)';
			$result = db_query($query, array(':rids' => array($userRoles[$userRoleID])));
			$uids = $result->fetchCol();
		}
  }
  //Load all emails into array
  foreach($uids as $userID => $userInfo){
  	$loadedUser = user_load($userInfo);
  	$emailsArray[$userInfo] = $loadedUser->mail;
  }
		
  /**
  * TODO: Make a settings page
  **/

  /**
   * Make function for super admins
   */
  if($userRoleID == 17 || $user->uid == 1){
 		$form['roles_to_email'] = array(
 			'#type' => 'select',
 			'#title' => t('Roles to Email?'),
 			'#options' => $torAdminRoleOptions,
 			'#description' => t('To whom would you like to send your email?'),
 		);
  }else{
  	$form['roles_to_email_markup_text'] = array(
  		'#type' => 'item',
  		'#markup' => '<h3>You will be sending emails to ' . $torAdminTitleOptions[$userRoleID] . '</h3>',
  	);
	  $form['roles_to_email'] = array(
  		'#type' => 'hidden',
  		'#value' => $emailsArray,
  	);
  	$form['roleIDs_to_email'] = array(
  		'#type' => 'hidden',
  		'#value' => $torAdminTitleOptions[$userRoleID],
  	);
	}
  $form['subject_of_emails'] = array(
  	'#title' => t('Subject'),
  	'#type' => 'textfield',
  	'#description' => t('The subject of the mass email'),
  	'#default_value' => '',
  	'#size' => 60, 
	  '#maxlength' => 128, 
  	'#required' => TRUE,
  );

  $form['message_of_email'] = array(
  	'#title' => t('Message'),
  	'#type' => 'textarea',
  	'#description' => t('The subject of the mass email'),
  	'#default_value' => '',
  );

  $form['send_emails'] = array(
  	'#value' => t('Send Email'),
  	'#type' => 'submit',
  );

	return $form;
}

function email_by_role_form_submit(&$form, &$form_state){
	global $user;
	$emailsArray = array();

	//IF user is superAdmin or if user is ToRAdmin, they can email any role
	if($user->uid == 1 || $user->roles == 17){
		$query = 'SELECT DISTINCT(ur.uid) 
	  	FROM {users_roles} AS ur
	  	WHERE ur.rid IN (:rids)';
		$result = db_query($query, array(':rids' => $form_state['values']['roles_to_email']));
		$uids = $result->fetchCol();

		foreach($uids as $userID => $userInfo){
  		$loadedUser = user_load($userInfo);
  		$emailsArray[$userInfo] = $loadedUser->mail;
  	}
  //If user is one of the other admins, the only emails they have access to are the roles for which they are admins to
	}else{
		$emailsArray = $form_state['values']['roles_to_email'];
	}

	$to = '';
	foreach($emailsArray as $uid => $emails){
		$to .= $emails . ',';
	}
	//Remove last comma
	$to = substr($to, 0, -1);
	$subject = $form_state['values']['subject_of_emails'];
	$message = $form_state['values']['message_of_email'];

	//Set content type
	$headers  = 'MIME-Version: 1.0' . "\r\n";
	$headers .= 'Content-type: text/html; charset=iso-8859-1' . "\r\n";
	$headers .= 'From: Tournament of Roses Application Committee <info@tofr.co>' . "\r\n";
	
	mail($to, $subject, $message, $headers);
	if($user->uid == 1 || $user->roles == 17){
		$roleName = user_role_load($form_state['values']['roles_to_email']);
		$roleName = $roleName->name;
		$roleName = explode(' ', $roleName);
		$roleName = $roleName[0];
	}
	else{
		$roleName = $form_state['values']['roleIDs_to_email'];
		$roleName = explode(' ', $roleName);
		$roleName = $roleName[0];
	}

	drupal_set_message('Your email was successfully sent to all ' . $roleName . ' entrants!');
}